
DROP TABLE BANK_ACCOUNTS;
CREATE TABLE BANK_ACCOUNTS(
    BANK_ACCOUNT_ID NUMBER PRIMARY KEY,
    BALANCE NUMBER(10,2),
    USER_ID NUMBER  
);

CREATE TABLE REGISTERED_USER(
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR2(50) NOT NULL,   
    BANK_ACCOUNT_ID NUMBER,
    SUPERUSER NUMBER
);

ALTER TABLE REGISTERED_USER MODIFY SUPERUSER DEFAULT 0;

ALTER TABLE BANK_ACCOUNTS 
ADD FOREIGN KEY (USER_ID) REFERENCES REGISTERED_USER(USER_ID);

ALTER TABLE REGISTERED_USER
ADD FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNTS(BANK_ACCOUNT_ID);

--CREATING SEQUENCE FOR USER_ID
CREATE SEQUENCE SQ_USER_ID
START WITH 1
INCREMENT BY 1;
--PUTTING SEQUENCE INTO A TRIGGER
CREATE OR REPLACE TRIGGER TR_INSERT_USER_ID
BEFORE INSERT ON REGISTERED_USER
FOR EACH ROW 
BEGIN
    SELECT SQ_USER_ID.NEXTVAL INTO:NEW.USER_ID FROM DUAL;
END;
  
--CREATING SEQUENCE FOR BANKG_ACCOUNT_ID
CREATE SEQUENCE SQ_BANK_ACCOUNT_ID
START WITH 20
INCREMENT BY 20;
--CREATING TRIGGER FOR SQ_BANK_ACCOUNT_ID
CREATE OR REPLACE TRIGGER TR_BANK_ACCOUNT_ID
BEFORE INSERT ON BANK_ACCOUNTS
FOR EACH ROW
BEGIN
    SELECT SQ_BANK_ACCOUNT_ID.NEXTVAL INTO:NEW.BANK_ACCOUNT_ID FROM DUAL;
END;




--ENTER USER AND MATCH FOREIGN KEY 
INSERT INTO REGISTERED_USER(USERNAME,USER_PASSWORD,SUPERUSER) VALUES('Monica','password',1);
INSERT INTO BANK_ACCOUNTS(BALANCE, USER_ID) VALUES(50000.00,41);
UPDATE REGISTERED_USER SET BANK_ACCOUNT_ID=480 WHERE USER_ID=41;

--ENTER USER AND MATCH FOREIGN KEY
INSERT INTO REGISTERED_USER(USERNAME,USER_PASSWORD,SUPERUSER) VALUES('Joey','orange',0);
INSERT INTO BANK_ACCOUNTS(BALANCE, USER_ID) VALUES(45000.00,42);
UPDATE REGISTERED_USER SET BANK_ACCOUNT_ID=500 WHERE USER_ID=42;

SELECT columns
FROM table1 
INNER JOIN table2
ON table1.column = table2.column;

INSERT INTO BANK_ACCOUNTS(BALANCE,USER_ID) VALUES (0,(SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'fahim'));

DELETE FROM BANK_ACCOUNTS WHERE USER_ID = (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'fahim') AND BALANCE = 0;

SELECT BALANCE FROM BANK_ACCOUNTS WHERE USER_ID = (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'Monica');

UPDATE BANK_ACCOUNTS SET BALANCE = BALANCE+10000 WHERE USER_ID = (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'Monica');

(SELECT  USER_ID FROM REGISTERED_USER WHERE USERNAME = 'Monica');

INSERT INTO BANK_ACCOUNTS(?, USER_ID) VALUES(?, (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = ?));

INSERT INTO BANK_ACCOUNTS(BALANCE,USER_ID) VALUES (70000,61);

UPDATE REGISTERED_USER SET BANK_ACCOUNT_ID=160 WHERE USER_ID=61;

SELECT BALANCE FROM BANK_ACCOUNTS WHERE USER_ID = (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'Gunther');

DELETE FROM BANK_ACCOUNTS WHERE USER_ID = (SELECT USER_ID FROM REGISTERED_USER WHERE USERNAME = 'Gunther');
